#ifndef FW_CONFIG_H
#define FW_CONFIG_H

/**
 * Mock fw_config.h for host-based testing.
 *
 * Provides board identity and feature flags that would normally be
 * generated by CMake from fw_config.h.in.
 */

#define FW_BOARD_NAME  "test_board"
#define FW_BOARD_MCU   "test_mcu"

/* Enable USB so we can test CDC code paths */
#ifndef FW_ENABLE_USB
#define FW_ENABLE_USB
#endif

#endif /* FW_CONFIG_H */
