/*
 * gen_8b10b_lut.c — Generate flat 8b/10b LUT from split-table encoder.
 *
 * Compile: gcc -o gen_8b10b_lut gen_8b10b_lut.c
 * Run:     ./gen_8b10b_lut
 *
 * Outputs C code for the flat LUT to stdout.
 */
#include <stdio.h>
#include <stdint.h>

/* 5b/6b table (copied from encode_8b10b.c) */
static const uint8_t enc_5b6b[32][2] = {
    { 0x38, 0x07 }, /* D.00 */
    { 0x3D, 0x22 }, /* D.01 */
    { 0x2D, 0x12 }, /* D.02 */
    { 0x31, 0x31 }, /* D.03 */
    { 0x35, 0x0A }, /* D.04 */
    { 0x29, 0x29 }, /* D.05 */
    { 0x19, 0x19 }, /* D.06 */
    { 0x38, 0x38 }, /* D.07 */
    { 0x39, 0x06 }, /* D.08 */
    { 0x25, 0x25 }, /* D.09 */
    { 0x15, 0x15 }, /* D.10 */
    { 0x34, 0x34 }, /* D.11 */
    { 0x0D, 0x0D }, /* D.12 */
    { 0x2C, 0x2C }, /* D.13 */
    { 0x1C, 0x1C }, /* D.14 */
    { 0x3A, 0x05 }, /* D.15 */
    { 0x36, 0x09 }, /* D.16 */
    { 0x23, 0x23 }, /* D.17 */
    { 0x13, 0x13 }, /* D.18 */
    { 0x32, 0x32 }, /* D.19 */
    { 0x0B, 0x0B }, /* D.20 */
    { 0x2A, 0x2A }, /* D.21 */
    { 0x1A, 0x1A }, /* D.22 */
    { 0x3B, 0x04 }, /* D.23 */
    { 0x37, 0x08 }, /* D.24 */
    { 0x26, 0x26 }, /* D.25 */
    { 0x16, 0x16 }, /* D.26 */
    { 0x33, 0x0C }, /* D.27 */
    { 0x0E, 0x0E }, /* D.28 */
    { 0x2E, 0x11 }, /* D.29 */
    { 0x1E, 0x21 }, /* D.30 */
    { 0x3E, 0x01 }, /* D.31 */
};

/* 3b/4b table (copied from encode_8b10b.c) */
static const uint8_t enc_3b4b[8][2] = {
    { 0x0B, 0x04 }, /* D.x.0 */
    { 0x09, 0x09 }, /* D.x.1 */
    { 0x05, 0x05 }, /* D.x.2 */
    { 0x0C, 0x03 }, /* D.x.3 */
    { 0x0D, 0x02 }, /* D.x.4 */
    { 0x0A, 0x0A }, /* D.x.5 */
    { 0x06, 0x06 }, /* D.x.6 */
    { 0x0E, 0x01 }, /* D.x.7 (primary) */
};

static int popcount8(uint8_t v)
{
    int c = 0;
    while (v) { c += v & 1; v >>= 1; }
    return c;
}

/*
 * Encode one byte using the split-table method.
 * rd: pointer to running disparity (-1 or +1), updated in place.
 * Returns 10-bit symbol in lower 10 bits.
 */
static uint16_t encode_byte(int8_t *rd, uint8_t byte)
{
    uint8_t edcba = byte & 0x1F;
    uint8_t hgf   = (byte >> 5) & 0x07;

    int rd_idx = (*rd > 0) ? 1 : 0;

    /* 5b/6b */
    uint8_t code_6b = enc_5b6b[edcba][rd_idx];
    int disp_6 = 2 * popcount8(code_6b & 0x3F) - 6;

    int8_t rd_after_6 = *rd + (int8_t)disp_6;
    if (rd_after_6 > 0) rd_after_6 = 1; else rd_after_6 = -1;

    /* 3b/4b */
    int rd_idx_4 = (rd_after_6 > 0) ? 1 : 0;
    uint8_t code_4b = enc_3b4b[hgf][rd_idx_4];
    int disp_4 = 2 * popcount8(code_4b & 0x0F) - 4;

    int8_t rd_final = rd_after_6 + (int8_t)disp_4;
    if (rd_final > 0) rd_final = 1; else rd_final = -1;

    *rd = rd_final;

    return (uint16_t)(((uint16_t)code_6b << 4) | code_4b);
}

int main(void)
{
    printf("/* Auto-generated by tools/gen_8b10b_lut.c — DO NOT EDIT */\n\n");

    const char *names[2] = { "enc_8b10b_rd_neg", "enc_8b10b_rd_pos" };
    int8_t init_rd[2] = { -1, +1 };

    for (int t = 0; t < 2; t++) {
        printf("static const uint16_t %s[256] = {\n", names[t]);
        for (int b = 0; b < 256; b++) {
            int8_t rd = init_rd[t];
            uint16_t sym = encode_byte(&rd, (uint8_t)b);

            /* Did RD flip? */
            uint8_t flip = (rd != init_rd[t]) ? 1 : 0;
            uint16_t entry = sym | ((uint16_t)flip << 10);

            if ((b & 7) == 0) printf("    ");
            printf("0x%03X", entry);
            if (b < 255) printf(",");
            if ((b & 7) == 7) {
                printf("  /* D.%d.%d – D.%d.%d */\n",
                       b - 7, (b - 7) >> 5, b & 0x1F, b >> 5);
            } else {
                printf(" ");
            }
        }
        printf("};\n\n");
    }

    return 0;
}
